version: '3'
 
services:
  fauxmo:
    build: .
    image: ghcr.io/servercontainers/fauxmo
    restart: always
    network_mode: host
    environment:
      FAUXMO_PLUGIN_COMMANDLINE_DEVICE_1_stuff_to_file: '                { "name": "output stuff to a file", "port": 49915, "on_cmd": "touch testfile.txt", "off_cmd": "rm testfile.txt", "state_cmd": "ls testfile.txt" }'


      FAUXMO_PLUGIN_HOMEASSISTANT_CONFIG: '            "ha_host": "192.168.0.50", "ha_port": 8123, "ha_protocol": "http", "ha_token": "abc123",'

      FAUXMO_PLUGIN_HOMEASSISTANT_DEVICE_1_my_fake_switch: '                { "name": "example Home Assistant device 1", "port": 12345, "entity_id": "switch.my_fake_switch" },'
      FAUXMO_PLUGIN_HOMEASSISTANT_DEVICE_2_my_fake_cover: '                { "name": "example Home Assistant device 2", "port": 12346, "entity_id": "switch.my_fake_cover" }'